    'use strict';
    const STORAGE_KEY='totoauth.accounts.v1';
    const SAMPLE={service:'RFC test account',username:'alice@example.com',secret:'GEZDGNBVGY3TQOJQGEZDGNBVGY3TQOJQ'};
    const snippets={
      python:`import base64, hashlib, hmac, struct, time\n\ndef totp(secret_b32, now=None):\n    key = base64.b32decode(secret_b32.upper())\n    counter = int((now or time.time()) // 30)\n    digest = hmac.new(key, struct.pack(">Q", counter), hashlib.sha1).digest()\n    offset = digest[-1] & 0x0f\n    binary = int.from_bytes(digest[offset:offset + 4], "big") & 0x7fffffff\n    return str(binary % 1_000_000).zfill(6)`,
      javascript:`async function totp(secretBytes, now = Date.now() / 1000) {\n  const counter = BigInt(Math.floor(now / 30));\n  const msg = new Uint8Array(8);\n  new DataView(msg.buffer).setBigUint64(0, counter);\n  const key = await crypto.subtle.importKey("raw", secretBytes, { name: "HMAC", hash: "SHA-1" }, false, ["sign"]);\n  const mac = new Uint8Array(await crypto.subtle.sign("HMAC", key, msg));\n  const offset = mac[mac.length - 1] & 0x0f;\n  const n = ((mac[offset] & 0x7f) << 24) | (mac[offset+1] << 16) | (mac[offset+2] << 8) | mac[offset+3];\n  return String((n >>> 0) % 1_000_000).padStart(6, "0");\n}`,
      go:`func TOTP(secret []byte, now time.Time) string {\n    counter := uint64(now.Unix() / 30)\n    var msg [8]byte\n    binary.BigEndian.PutUint64(msg[:], counter)\n    mac := hmac.New(sha1.New, secret)\n    mac.Write(msg[:])\n    sum := mac.Sum(nil)\n    offset := sum[len(sum)-1] & 0x0f\n    value := binary.BigEndian.Uint32(sum[offset:offset+4]) & 0x7fffffff\n    return fmt.Sprintf("%06d", value%1_000_000)\n}\n// imports: crypto/hmac, crypto/sha1, encoding/binary, fmt, time`,
      java:`static String totp(byte[] secret, long unixSeconds) throws Exception {\n    long counter = unixSeconds / 30;\n    byte[] msg = ByteBuffer.allocate(8).putLong(counter).array();\n    Mac mac = Mac.getInstance("HmacSHA1");\n    mac.init(new SecretKeySpec(secret, "HmacSHA1"));\n    byte[] hash = mac.doFinal(msg);\n    int offset = hash[hash.length - 1] & 0x0f;\n    int value = ((hash[offset] & 0x7f) << 24) | ((hash[offset+1] & 0xff) << 16)\n        | ((hash[offset+2] & 0xff) << 8) | (hash[offset+3] & 0xff);\n    return String.format(Locale.ROOT, "%06d", value % 1_000_000);\n}\n// imports: javax.crypto.Mac, javax.crypto.spec.SecretKeySpec, java.nio.ByteBuffer`,
      rust:`use hmac::{Hmac, Mac};\nuse sha1::Sha1;\n\nfn totp(secret: &[u8], unix_seconds: u64) -> String {\n    let counter = unix_seconds / 30;\n    let mut mac = Hmac::<Sha1>::new_from_slice(secret).unwrap();\n    mac.update(&counter.to_be_bytes());\n    let hash = mac.finalize().into_bytes();\n    let offset = (hash[19] & 0x0f) as usize;\n    let value = (u32::from_be_bytes(hash[offset..offset + 4].try_into().unwrap()) & 0x7fff_ffff) % 1_000_000;\n    format!("{value:06}")\n}\n// Cargo.toml: hmac = "0.12", sha1 = "0.10"`
    };
    const accountList=document.querySelector('#account-list'),accountCount=document.querySelector('#account-count'),clearButton=document.querySelector('#clear-button'),dialog=document.querySelector('#account-dialog'),form=document.querySelector('#account-form'),toast=document.querySelector('#toast');
    let accounts=loadAccounts(),toastTimer;
    function loadAccounts(){try{const saved=JSON.parse(localStorage.getItem(STORAGE_KEY)||'[]');return Array.isArray(saved)?saved.filter(item=>item&&typeof item.id==='string'&&typeof item.secret==='string'):[]}catch{return[]}}
    function saveAccounts(){try{localStorage.setItem(STORAGE_KEY,JSON.stringify(accounts));return true}catch{showToast('Could not save: browser storage is unavailable.');return false}}
    function decodeBase32(value){const alphabet='ABCDEFGHIJKLMNOPQRSTUVWXYZ234567',normalized=value.toUpperCase().replace(/[\s=-]/g,'');if(!normalized||!/^[A-Z2-7]+$/.test(normalized))throw Error('Enter a valid Base32 secret (letters A–Z and digits 2–7).');let bits=0,buffer=0;const bytes=[];for(const char of normalized){buffer=(buffer<<5)|alphabet.indexOf(char);bits+=5;if(bits>=8){bits-=8;bytes.push((buffer>>bits)&255)}}if(bytes.length<10)throw Error('Secret is too short. Use at least 16 Base32 characters.');return new Uint8Array(bytes)}
    async function generateTotp(secret,seconds=Date.now()/1000){const bytes=decodeBase32(secret),counter=BigInt(Math.floor(seconds/30)),message=new Uint8Array(8);new DataView(message.buffer).setBigUint64(0,counter);const key=await crypto.subtle.importKey('raw',bytes,{name:'HMAC',hash:'SHA-1'},false,['sign']);const digest=new Uint8Array(await crypto.subtle.sign('HMAC',key,message));const offset=digest[digest.length-1]&15;const binary=((digest[offset]&127)<<24)|(digest[offset+1]<<16)|(digest[offset+2]<<8)|digest[offset+3];return String((binary>>>0)%1000000).padStart(6,'0')}
    function showToast(message){toast.textContent=message;toast.classList.add('show');clearTimeout(toastTimer);toastTimer=setTimeout(()=>toast.classList.remove('show'),2600)}
    function makeCard(account){const card=document.createElement('article');card.className='account';card.dataset.id=account.id;const top=document.createElement('div');top.className='account-top';const identity=document.createElement('div');identity.className='account-identity';const mark=document.createElement('span');mark.className='account-icon';mark.setAttribute('aria-hidden','true');mark.textContent=account.service.trim().split(/\s+/).slice(0,2).map(word=>word[0]||'').join('').toUpperCase()||'2F';const labels=document.createElement('div');labels.style.minWidth='0';const service=document.createElement('div');service.className='account-service';service.textContent=account.service;const username=document.createElement('div');username.className='account-user';username.textContent=account.username;labels.append(service,username);identity.append(mark,labels);const remove=document.createElement('button');remove.className='icon-button';remove.type='button';remove.title=`Remove ${account.service}`;remove.setAttribute('aria-label',`Remove ${account.service}`);remove.textContent='×';remove.addEventListener('click',()=>{accounts=accounts.filter(item=>item.id!==account.id);if(saveAccounts())render()});top.append(identity,remove);const row=document.createElement('div');row.className='code-row';const code=document.createElement('span');code.className='otp-code';code.textContent='------';const copy=document.createElement('button');copy.className='copy-button';copy.type='button';copy.textContent='Copy';copy.addEventListener('click',async()=>{if(!/^\d{6}$/.test(code.textContent))return;try{await navigator.clipboard.writeText(code.textContent);showToast('Code copied to clipboard.')}catch{showToast('Clipboard access is unavailable in this context.')}});row.append(code,copy);const expiry=document.createElement('div');expiry.className='expiry';const track=document.createElement('span');track.className='expiry-track';const fill=document.createElement('span');fill.className='expiry-fill';track.append(fill);const left=document.createElement('span');left.className='time-left';expiry.append(track,left);card.append(top,row,expiry);return card}
    function render(){accountCount.innerHTML=`${accounts.length} <small>saved locally</small>`;clearButton.hidden=accounts.length===0;if(!accounts.length){const empty=document.createElement('div');empty.className='empty-state';empty.innerHTML='<div><span class="empty-mark">+</span><strong>No accounts saved</strong><p>Add a secret or load the RFC sample to see a live code.</p></div>';accountList.replaceChildren(empty);return}accountList.replaceChildren(...accounts.map(makeCard));refreshCodes()}
    async function refreshCodes(){const now=Date.now()/1000,left=30-(Math.floor(now)%30),progress=left/30*100;for(const card of accountList.querySelectorAll('.account')){const account=accounts.find(item=>item.id===card.dataset.id);if(!account)continue;const code=card.querySelector('.otp-code');try{code.textContent=await generateTotp(account.secret,now);code.setAttribute('aria-label',`One-time code ${code.textContent}`)}catch{code.textContent='ERROR';code.setAttribute('aria-label','Could not generate code. Remove and re-add this account.')}card.querySelector('.time-left').textContent=`${left}s`;card.querySelector('.expiry-fill').style.width=`${progress}%`}}
    document.querySelector('#add-button').addEventListener('click',()=>{form.reset();document.querySelector('#form-error').textContent='';dialog.showModal();document.querySelector('#service-input').focus()});document.querySelector('#close-dialog').addEventListener('click',()=>dialog.close());document.querySelector('#cancel-dialog').addEventListener('click',()=>dialog.close());dialog.addEventListener('click',event=>{if(event.target===dialog)dialog.close()});
    form.addEventListener('submit',async event=>{event.preventDefault();const service=document.querySelector('#service-input').value.trim(),username=document.querySelector('#username-input').value.trim(),secret=document.querySelector('#secret-input').value.trim(),error=document.querySelector('#form-error');if(!service||!username){error.textContent='Enter both a service name and an account label.';return}try{decodeBase32(secret);await generateTotp(secret)}catch(reason){error.textContent=reason.message||'That secret could not be used.';return}accounts.push({id:crypto.randomUUID(),service,username,secret:secret.toUpperCase().replace(/[\s=-]/g,'')});if(saveAccounts()){dialog.close();render();showToast('Account saved in this browser.')}});
    document.querySelector('#sample-button').addEventListener('click',()=>{if(accounts.some(item=>item.service===SAMPLE.service&&item.username===SAMPLE.username)){showToast('The RFC sample account is already loaded.');return}accounts.push({id:crypto.randomUUID(),...SAMPLE});if(saveAccounts()){render();showToast('RFC sample account loaded.')}});
    clearButton.addEventListener('click',()=>{if(!confirm('Remove every saved account from this browser? This cannot be undone.'))return;accounts=[];if(saveAccounts()){render();showToast('All local accounts were removed.')}});
    document.querySelectorAll('.tab-button').forEach(button=>{button.addEventListener('click',()=>{document.querySelectorAll('.tab-button').forEach(tab=>tab.setAttribute('aria-selected',String(tab===button)));const panel=document.querySelector('#code-snippet');panel.setAttribute('aria-labelledby',button.id);panel.querySelector('code').textContent=snippets[button.dataset.language]});button.addEventListener('keydown',event=>{if(!['ArrowLeft','ArrowRight'].includes(event.key))return;event.preventDefault();const tabs=[...document.querySelectorAll('.tab-button')],i=tabs.indexOf(button),next=tabs[(i+(event.key==='ArrowRight'?1:tabs.length-1))%tabs.length];next.focus();next.click()})});
    document.querySelector('#snippet-copy').addEventListener('click',async()=>{try{await navigator.clipboard.writeText(document.querySelector('#code-snippet code').textContent);showToast('Code template copied.')}catch{showToast('Clipboard access is unavailable in this context.')}});
    document.querySelector('#code-snippet code').textContent=snippets.python;render();setInterval(refreshCodes,1000);